Job description file for merging rms dbGAP vcfs
Alexey Larionov, 10Jun2016

TEMPLATE v1

=========== Data location and analysis settings =============

data_server: admin@mgqnap.medschl.cam.ac.uk
project_location: /share/mae

project: rms_dbGAP

input_vcfs_folder: s04_filtered_vcfs

output_folder: s05_merged_vcf_v1

Remove_project_folder_from_HPC_scratch_after_run: no

============= Additional mgqnap settings ====================

mgqnap_user: mae
mgqnap_group: mtgroup

======================= HPC settings ========================

working_folder: /scratch/medgen/users/alexey

Account_to_use_on_HPC: TISCHKOWITZ-SL2
Max_time_to_request_(hrs.min.sec): 10.00.00

==================== Step summary =======================

#Merge and QC rms dbGAP vcfs

===================== Standard settings =====================

scripts_folder: /scratch/medgen/scripts/rms_pipeline_06.16/p05_rms_merge_vcfs
start_script: a00_start_pipeline.sh

Tools
-----

tools_folder: /scratch/medgen/tools
java7: java/jre1.7.0_76/bin/java
gatk: gatk/gatk-3.4-46/GenomeAnalysisTK.jar

bcftools: bcftools/bcftools-1.2/bin/bcftools
plot_vcfstats: bcftools/bcftools-1.2/bin/plot-vcfstats

Updated version of Python matplotlib library for plot-vcfstats script
python_bin: python/python_2.7.10/bin/

r_folder: r/R-3.2.0/bin

r_bin_folder: r/R-3.2.2/bin/
r_lib_folder: r/R-3.2.2/lib64/R/library

Note about using different R versions
-------------------------------------
R-3.2.0 is used here for plotting in GATK-VQSR, 
which requires a specific set of R-libraries.
For being accessable by GATK, R-3.2.0 is added to PATH.
  
R-3.2.2 is used here to genereate html and pdf reports with rmarkdown.
Generating reports with Rmarkdown is pernickety about environment. 
It requires recent versions of several system libraries
and a number of additional R libraries to be pre-installed.
The external libraries are loaded as modules in *.sb.sh script:
module load gcc/5.2.0
module load boost/1.50.0
module load texlive/2015
module load pandoc/1.15.2.1
Rmarkdown library has to be installed in the r_lib_folder
shown above. 

Historically, at the time of the scripts preparation, it happened
that different sets of libraries were available in different versions
of R installed in the toolbox. This resulted to the temporary configuration
of using two different R versions at the same time. Then, there was 
no time and need to change it.  

See details details about required R-libraries in the 
r-installation notes in the tools folder.

Resources
---------

resources_folder: /scratch/medgen/resources

decompressed_bundle_folder: gatk_bundle/hg19/decompressed

ref_genome: ucsc.hg19.fasta
hapmap: hapmap_3.3.hg19.sites.vcf
omni: 1000G_omni2.5.hg19.sites.vcf
phase1_1k_hc: 1000G_phase1.snps.high_confidence.hg19.sites.vcf
dbsnp_138: dbsnp_138.hg19.vcf
dbsnp_138_sites129: dbsnp_138.hg19.excluding_sites_after_129.vcf
mills: Mills_and_1000G_gold_standard.indels.hg19.sites.vcf

broad_exomes_intervals: broad_human_exome_hg19.interval_list

ph3_1k_folder: phase3_1k_release20130502/vcfs
ph3_1k_vcf: ALL.wgs.phase3_shapeit2_mvncall_integrated_v5a.20130502.hg19.sites.vcf

fa_mask_folder: phase3_1k_release20130502/variants_with_frequent_ALT_allele_hg19
fa_mask_90: FAA_mask_90.vcf
fa_mask_95: FAA_mask_95.vcf
fa_mask_99: FAA_mask_99.vcf
fa_mask_100: FAA_mask_100.vcf

Working sub-folders
-------------------

logs_folder: logs
vqsr_folder: vqsr
vcfstats_folder: vcfstats
histograms_folder: histograms
